name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Cambia a la rama que uses para tu código principal (ej. master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Usa la última versión de actions/checkout

      # Aquí va el bloque de código que te di arriba
      - name: Deploy React to GitHub Pages
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          checkout: true
          path: build # Asegúrate de que esta sea la carpeta correcta (build o dist)
          install_command: npm ci
          build_command: npm run build
          caching: true
